# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `browserslist_useragent` gem.
# Please instead update this file by running `tapioca generate`.

# typed: true

module BrowserslistUseragent
end

class BrowserslistUseragent::Match
  def initialize(queries, user_agent_string); end

  def browser?; end
  def queries; end
  def user_agent_string; end
  def version?(allow_higher: T.unsafe(nil)); end

  private

  def match_higher_version?(semantic, query_version); end
  def match_semantic_version(semantic, allow_higher:); end
  def match_version?(semantic, query_version); end
  def user_agent; end
end

class BrowserslistUseragent::QueryNormalizer
  def initialize(query); end

  def call; end
  def query; end
end

BrowserslistUseragent::QueryNormalizer::NORMALIZED_NAMES = T.let(T.unsafe(nil), Hash)

class BrowserslistUseragent::Resolver
  def initialize(user_agent_string); end

  def call; end
  def user_agent_string; end

  class << self
    def user_agent_parser; end
  end
end

BrowserslistUseragent::VERSION = T.let(T.unsafe(nil), String)

class BrowserslistUseragent::VersionNormalizer
  def initialize(version); end

  def call; end
  def version; end
end
