# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `buffered-logger` gem.
# Please instead update this file by running `tapioca generate`.

# typed: true

class BufferedLogger < ::ActiveSupport::Logger
  def initialize(*_); end

  def current_log; end
  def end; end
  def flush; end
  def start; end
  def started?; end
end

class BufferedLogger::AlreadyStartedError < ::StandardError
end

class BufferedLogger::LogDeviceProxy
  def initialize(logdev); end

  def close; end
  def current_log; end
  def end; end
  def flush; end
  def start; end
  def started?; end
  def write(message); end

  private

  def destroy_thread_local; end
  def string_io; end
  def string_io=(string_io); end
end

BufferedLogger::LogDeviceProxy::THREAD_LOCAL_VAR_NAME = T.let(T.unsafe(nil), Symbol)

class BufferedLogger::Middleware
  def initialize(app, logger); end

  def call(env); end
end

class BufferedLogger::NotStartedError < ::StandardError
end

BufferedLogger::VERSION = T.let(T.unsafe(nil), String)
