# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `digest-crc` gem.
# Please instead update this file by running `tapioca generate`.

# typed: true

class Digest::CRC < ::Digest::Class
  def initialize; end

  def <<(data); end
  def block_length; end
  def checksum; end
  def digest_length; end
  def finish; end
  def reset; end
  def update(data); end

  class << self
    def checksum(data); end
    def pack(crc); end
  end
end

Digest::CRC::INIT_CRC = T.let(T.unsafe(nil), Integer)

Digest::CRC::TABLE = T.let(T.unsafe(nil), Array)

Digest::CRC::WIDTH = T.let(T.unsafe(nil), Integer)

Digest::CRC::XOR_MASK = T.let(T.unsafe(nil), Integer)

class Digest::CRC1 < ::Digest::CRC
  def update(data); end

  class << self
    def pack(crc); end
  end
end

class Digest::CRC15 < ::Digest::CRC
  def update(_); end

  class << self
    def pack(crc); end
  end
end

Digest::CRC15::TABLE = T.let(T.unsafe(nil), Array)

Digest::CRC15::WIDTH = T.let(T.unsafe(nil), Integer)

class Digest::CRC16 < ::Digest::CRC
  def update(_); end

  class << self
    def pack(crc); end
  end
end

Digest::CRC16::INIT_CRC = T.let(T.unsafe(nil), Integer)

Digest::CRC16::TABLE = T.let(T.unsafe(nil), Array)

Digest::CRC16::WIDTH = T.let(T.unsafe(nil), Integer)

class Digest::CRC24 < ::Digest::CRC
  def update(_); end

  class << self
    def pack(crc); end
  end
end

Digest::CRC24::INIT_CRC = T.let(T.unsafe(nil), Integer)

Digest::CRC24::TABLE = T.let(T.unsafe(nil), Array)

Digest::CRC24::WIDTH = T.let(T.unsafe(nil), Integer)

class Digest::CRC32 < ::Digest::CRC
  def update(_); end

  class << self
    def pack(crc); end
  end
end

Digest::CRC32::INIT_CRC = T.let(T.unsafe(nil), Integer)

Digest::CRC32::TABLE = T.let(T.unsafe(nil), Array)

Digest::CRC32::WIDTH = T.let(T.unsafe(nil), Integer)

Digest::CRC32::XOR_MASK = T.let(T.unsafe(nil), Integer)

class Digest::CRC32c < ::Digest::CRC32
  def update(_); end
end

Digest::CRC32c::TABLE = T.let(T.unsafe(nil), Array)

class Digest::CRC5 < ::Digest::CRC
  def initialize; end

  def update(_); end

  class << self
    def pack(crc); end
  end
end

Digest::CRC5::CRC_MASK = T.let(T.unsafe(nil), Integer)

Digest::CRC5::INIT_CRC = T.let(T.unsafe(nil), Integer)

Digest::CRC5::TABLE = T.let(T.unsafe(nil), Array)

Digest::CRC5::WIDTH = T.let(T.unsafe(nil), Integer)

Digest::CRC5::XOR_MASK = T.let(T.unsafe(nil), Integer)

class Digest::CRC64 < ::Digest::CRC
  def update(_); end

  class << self
    def pack(crc); end
  end
end

Digest::CRC64::INIT_CRC = T.let(T.unsafe(nil), Integer)

Digest::CRC64::TABLE = T.let(T.unsafe(nil), Array)

Digest::CRC64::WIDTH = T.let(T.unsafe(nil), Integer)

Digest::CRC64::XOR_MASK = T.let(T.unsafe(nil), Integer)

class Digest::CRC8 < ::Digest::CRC
  def update(_); end

  class << self
    def pack(crc); end
  end
end

Digest::CRC8::INIT_CRC = T.let(T.unsafe(nil), Integer)

Digest::CRC8::TABLE = T.let(T.unsafe(nil), Array)

Digest::CRC8::WIDTH = T.let(T.unsafe(nil), Integer)

class Digest::CRC8_1Wire < ::Digest::CRC8
  def update(_); end
end

Digest::CRC8_1Wire::TABLE = T.let(T.unsafe(nil), Array)
