# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rails-reverse-proxy` gem.
# Please instead update this file by running `tapioca generate`.

# typed: true

module ReverseProxy
  extend(::ReverseProxy)

  def version; end
end

class ReverseProxy::Client
  def initialize(url); end

  def callbacks; end
  def callbacks=(_); end
  def on_complete(&block); end
  def on_connect(&block); end
  def on_error(&block); end
  def on_missing(&block); end
  def on_redirect(&block); end
  def on_response(&block); end
  def on_set_cookies(&block); end
  def on_success(&block); end
  def request(env, options = T.unsafe(nil), &block); end
  def url; end
  def url=(_); end

  private

  def extract_http_request_headers(env); end
  def parse_cookie(cookie_str); end
  def reconstruct_header_name(name); end
end

ReverseProxy::Client::COOKIE_PARAM_PATTERN = T.let(T.unsafe(nil), Regexp)

ReverseProxy::Client::COOKIE_SPLIT_PATTERN = T.let(T.unsafe(nil), Regexp)

module ReverseProxy::Controller
  def reverse_proxy(proxy_url, options = T.unsafe(nil)); end
end
