# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `semantic` gem.
# Please instead update this file by running `tapioca generate`.

# typed: true

module Semantic
end

Semantic::GEM_VERSION = T.let(T.unsafe(nil), String)

class Semantic::Version
  include(::Comparable)

  def initialize(version_str); end

  def <=>(other_version); end
  def build; end
  def build=(b); end
  def compare_pre(prea, preb); end
  def eql?(other_version); end
  def hash; end
  def identifiers(pre); end
  def increment!(term); end
  def major; end
  def major!; end
  def major=(_); end
  def minor; end
  def minor!; end
  def minor=(_); end
  def patch; end
  def patch!; end
  def patch=(_); end
  def pre; end
  def pre=(_); end
  def satisfied_by?(versions); end
  def satisfies?(other_version); end
  def to_a; end
  def to_array; end
  def to_h; end
  def to_hash; end
  def to_s; end
  def to_string; end

  private

  def pad_version_string(version_string); end
  def pessimistic_match?(other_version_string); end
  def satisfies_comparator?(comparator, other_version_string); end
  def semverified(version_string); end
  def tilde_matches?(other_version_string); end
end

Semantic::Version::SemVerRegexp = T.let(T.unsafe(nil), Regexp)
