name: hello-world

type: rails-react

up:
  - homebrew:
      - mysql-client@5.7:
          or: [mysql@5.7]
          conflicts: [mysql-connector-c, mysql, mysql-client]
    # - another_package
  - ruby: 2.7.2
  - node:
      version: v12.18.4
      yarn: 1.13.0
  - bundler
  - railgun
  - database:
      bootstrap: bin/rails db:create db:migrate db:schema:load
      migrate: bin/rails db:migrate db:test:prepare
      host: hello-world.railgun
      user: root
      password: ''
      database: hello_world_development
  - custom:
      name: sewing-kit asset compilation
      met?: '[[ -d tmp/cache/assets/sewing-kit/webpack ]]'
      meet: yarn run sewing-kit build --mode development

server:
  port: 34251

commands:
  console: bin/rails console
  test:
    syntax:
      argument: file
      optional: args...
    run: cd $USER_PWD && bin/rails test $@
  typecheck:
    desc: 'run Sorbet typechecking and sewing-kit typechecking'
    aliases: ['tc']
    depends-railgun: false
    run: bin/srb tc && yarn run sewing-kit type-check
    subcommands:
      ruby:
        desc: 'run Sorbet typechecking'
        run: bin/srb tc
      javascript:
        desc: 'run sewing-kit typechecking for front-end files'
        run: yarn run sewing-kit type-check
  update-rbis:
    desc: 'updates the RBI files corresponding to gems listed in the Gemfile'
    depends-railgun: false
    run: bin/tapioca sync
  style:
    desc: 'Run rubocop and sewing-kit lint checks'
    run: cd $USER_PWD && bundle exec rubocop && yarn sewing-kit lint
    subcommands:
      ruby:
        syntax:
          optional: --include-branch-commits --all-cops
        desc: 'Run Rubocop checks. Add --include-branch-commits to run on all files changed on the current branch. Add --all-cops to run all the cops.'
        run: cd $USER_PWD && bundle exec rubocop
      javascript:
        desc: 'Run sewing-kit linting to check styling for front-end files'
        run: cd $USER_PWD && yarn sewing-kit lint
  graphql-dump:
    desc: 'Dump the GraphQL schema'
    run: bin/rails graphql:schema:dump

# These use fuzzy-matching, so you can (e.g.) `dev open app`
open:
  'My Application': https://hello-world.myshopify.io
  graphiql: https://hello-world.myshopify.io/graphiql
  #ops:
  # - https://datadog.link
  # - https://bugsnag.link
  # - https://kafka.link
